"""Emit the captured init sequence as a Python list, straight from the pcap."""
import struct

data = open("bio_all.pcap", "rb").read()
off, ctrl = 24, []
while off + 16 <= len(data):
    ts, tus, incl, orig = struct.unpack("<IIII", data[off:off+16]); off += 16
    body = data[off:off+incl]; off += incl
    if len(body) < 28: continue
    hlen, irp, status, func, info, bus, dev, ep, tr, dlen = struct.unpack("<HQIHBHHBBI", body[:27])
    if tr == 2 and body[27] == 0:
        p = body[hlen:hlen+dlen]
        if len(p) >= 8:
            ctrl.append((ts + tus/1e6,) + struct.unpack("<BBHHH", p[:8]))

t0 = ctrl[0][0]
writes = [(round(t-t0, 3), widx, wval) for t, bmrt, breq, wval, widx, wlen in ctrl
          if bmrt == 0x40 and breq == 0x01]

with open("init_writes.py", "w") as f:
    f.write('"""EM2860 init sequence captured from the Keeler vendor driver.\n\n')
    f.write('(delay_s, register, value) -- delay is relative to the first write.\n')
    f.write('Generated by gen_init.py from vendor/net2860_driver/capture/bio_all.pcap.\n"""\n\n')
    f.write("INIT_WRITES = [\n")
    for t, reg, val in writes:
        f.write(f"    ({t:6.3f}, 0x{reg:02x}, 0x{val:02x}),\n")
    f.write("]\n")
print(f"wrote init_writes.py with {len(writes)} writes")
